---
- hosts: all
  become: yes
  become_method: sudo
  vars:
    - touroperator_connstr: "Server=db,1433;TrustServerCertificate=Yes;Database=TourDB;UID=sa;PWD=password123!"
  roles:
    - geerlingguy.docker
    - touroperator
    
  tasks:
    - name: Restart touroperator
      ansible.builtin.service:
        name: touroperator
        state: restarted
        enabled: true

