version: "3"

services:
  touroperator:
    image: quay.io/radams15/touroperator:latest
    environment:
        - SQLCONNSTR_DefaultConnection={{ touroperator_connstr }}
    ports:
        - 9876:80
    depends_on:
        - db
    restart: unless-stopped
  
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=password123!
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
    volumes:
      - ./db:/var/opt/mssql/data/:z
